---
  header_logo_url: /logo-geotri.webp
  header_logo_text: GeoTri (BETA)
  header_links:
    - label: Home
      link: /

    - label: Bibliography
      link: https://bibtri.cepave.edu.ar/

    - label: About
      link: /about
